# GitHub Generated Files Configuration
# This file helps GitHub identify AI-generated or machine-generated content

version: 1

# Files that are partially or fully AI-generated
ai_generated:
  - "ytsprint/lib_yt_api.py"
  - "ytsprint/lib_date_utils.py"
  - "ytsprint/version.py"
  - "tests/test_yt_api.py"
  - "tests/test_version.py"
  - "Dockerfile.debian"
  - "Dockerfile.windows"
  - ".dockerignore"
  - "scripts/build-linux.sh"
  - "scripts/build-windows-amd64.sh"
  - "scripts/build-macos.sh"
  - "scripts/push-multi-ghcr.sh"
  - ".github/workflows/build-binaries.yml"

# Documentation that mentions AI collaboration
documentation:
  - "README.md"
  - "CHANGELOG.md"
  - "OSX_BUILD.md"
  - "AGENTS.md"

# Collaboration model
collaboration_type: "human-ai"
ai_tools:
  - "GitHub Copilot (Claude 4 Sonnet)"
  - "OpenAI Codex CLI"

# Human oversight and validation
human_verified: true
