# GitHub Generated Files Configuration
# This file helps GitHub identify AI-generated or machine-generated content

version: 1

# Files that are partially or fully AI-generated
ai_generated:
  - ".dockerignore"
  - ".gitignore"
  - ".pymarkdownlnt.json"
  - ".python-version"
  - ".yamllint.yaml"
  - ".github/generated-files.yml"
  - ".github/workflows/build-binaries.yml"
  - "AGENTS.md"
  - "CHANGELOG.md"
  - "Dockerfile"
  - "Dockerfile.build"
  - "LICENSE"
  - "OSX_BUILD.md"
  - "README.md"
  - "pyproject.toml"
  - "requirements.txt"
  - "scripts/build-linux-docker.sh"
  - "scripts/build-runtime.sh"
  - "scripts/internal/prepare-linux-deps.sh"
  - "scripts/linux-build.sh"
  - "scripts/linters.sh"
  - "scripts/macos-build.sh"
  - "scripts/windows-build.ps1"
  - "tests/conftest.py"
  - "tests/test_cli.py"
  - "tests/test_daemon_runner.py"
  - "tests/test_default_sprint.py"
  - "tests/test_default_sprint_errors.py"
  - "tests/test_version.py"
  - "tests/test_yt_api.py"
  - "ytsprint/__init__.py"
  - "ytsprint/cli.py"
  - "ytsprint/lib_daemon.py"
  - "ytsprint/lib_date_utils.py"
  - "ytsprint/lib_sprint.py"
  - "ytsprint/lib_yt_api.py"
  - "ytsprint/version.py"

# Documentation that mentions AI collaboration
documentation:
  - "README.md"
  - "CHANGELOG.md"
  - "OSX_BUILD.md"
  - "AGENTS.md"

# Collaboration model
collaboration_type: "human-ai"
ai_tools:
  - "GitHub Copilot (Claude 4 Sonnet)"
  - "OpenAI Codex CLI"

# Human oversight and validation
human_verified: true
